site_name: COMP423 Course Notes
theme:
  name: material
  # light and dark mode addition
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # copy and paste commands
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select

markdown_extensions:
  # Extra extensions
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - admonition
  - attr_list
  - md_in_html